name: CI

on:
    push:
    workflow_dispatch:

env:
  CYPRESS_API_KEY: 4aa6a711-8f69-4d2d-8d49-64dd7adc3911

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read

jobs:

  run-cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies and run Cypress tests
        run: |
          npm install cypress
          npx cypress run --record --key ${{env.CYPRESS_API_KEY}}