name: CI

on:
  push:
  workflow_dispatch:
  workflow_call:

permissions:
  id-token: write
  contents: read

jobs:

  cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: GivEnergy/QA-Automation-Scripts

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.10.0'

      - name: Install Cypress
        run: npm ci

      - name: Run Cypress tests
        run: npx cypress run --record --key ${{secrets.CYPRESS_RECORD_KEY}} --env adminUsername=${{ secrets.CYPRESS_ENV }}
