name: CI

on:
  push:
  workflow_dispatch:
  workflow_call:
    secrets:
      CYPRESS_RECORD_KEY:
        required: true
      CYPRESS_ENV:
        required: true

permissions:
  id-token: write
  contents: read

jobs:

  cypress-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ci_index: [0, 1]
        ci_total: [2]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: GivEnergy/QA-Automation-Scripts

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.10.0'

      - name: Install Cypress
        run: npm ci

      - name: Run Cypress tests
        run: npx cypress run --record --key ${{ secrets.CYPRESS_RECORD_KEY }} --env ${{ secrets.CYPRESS_ENV }} --browser ${{ matrix.browser }} --parallel