name: CI

on:
  push:
  workflow_dispatch:
  workflow_call:
    secrets:
      CYPRESS_RECORD_KEY:
        required: true
      CYPRESS_ENV:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  checkout-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: GivEnergy/QA-Automation-Scripts

  cypress-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        containers: [ 1, 2 ]

    steps:
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          record: true
          parallel: true
          env:
            ${{ secrets.CYPRESS_ENV }}
            ${{ secrets.CYPRESS_RECORD_KEY }}