name: CI

on:
  push:
  workflow_dispatch:

env:
  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
  ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
  CUSTOMER_USERNAME: ${{ secrets.CUSTOMER_USERNAME }}
  CUSTOMER_PASSWORD: ${{ secrets.CUSTOMER_PASSWORD }}
  ENGINEER_USERNAME: ${{ secrets.ENGINEER_USERNAME }}
  ENGINEER_PASSWORD: ${{ secrets.ENGINEER_PASSWORD }}
  

permissions:
  id-token: write
  contents: read

jobs:

  cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Cypress
        run: npm install cypress

      - name: Run Cypress tests
        run: npx cypress run --record --key ${{env.CYPRESS_RECORD_KEY}} --env adminUsername=$ADMIN_USERNAME --env adminPassword=$ADMIN_PASSWORD --env customerUsername=$CUSTOMER_USERNAME --env customerPassword=$CUSTOMER_PASSWORD --env engineerUsername=$ENGINEER_USERNAME --env engineerPassword=$ENGINEER_PASSWORD
