name: CI

on:
  push:
  workflow_dispatch:
  workflow_call:

env:
  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  CYPRESS_ENV: ${{ secrets.CYPRESS_ENV }}
  

permissions:
  id-token: write
  contents: read

jobs:

  cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Cypress
        run: npm install cypress

      - name: Run Cypress tests
        run: npx cypress run --record --key ${{env.CYPRESS_RECORD_KEY}} --env adminUsername=${{ env.CYPRESS_ENV }}
